/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectotenis;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import proyectotenis.CrearUsuario;

/**
 *
 * @author Diego
 */
public class inicio extends javax.swing.JFrame {

    public inicio() {
        initComponents();
       //setIconImage(new ImageIcon(getClass().getResource("/fotos/fondo.png")).getImage());
        getIconImage();
       login.conectdb();

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userinv = new javax.swing.JTextField();
        palabra = new javax.swing.JTextField();
        panelsuperior = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        loguear = new javax.swing.JPanel();
        usuario = new javax.swing.JTextField();
        registrar = new javax.swing.JLabel();
        textouser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contraseña = new javax.swing.JPasswordField();
        mostrar = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        Texto = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        userinv.setText("jTextField1");

        palabra.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(new java.awt.Color(242, 242, 242));
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(null);

        panelsuperior.setBackground(new java.awt.Color(245, 225, 39));
        panelsuperior.setLayout(null);

        jLabel2.setBackground(panelsuperior.getBackground());
        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel2.setText("-");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jLabel2.setOpaque(true);
        panelsuperior.add(jLabel2);
        jLabel2.setBounds(334, 0, 16, 16);

        jLabel5.setBackground(panelsuperior.getBackground());
        jLabel5.setText("❐");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jLabel5.setOpaque(true);
        panelsuperior.add(jLabel5);
        jLabel5.setBounds(356, 2, 20, 20);

        jLabel1.setBackground(panelsuperior.getBackground());
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jLabel1.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jLabel1VetoableChange(evt);
            }
        });
        jLabel1.setOpaque(true);
        panelsuperior.add(jLabel1);
        jLabel1.setBounds(382, 0, 28, 20);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 0));
        jLabel4.setText("TENIS");
        panelsuperior.add(jLabel4);
        jLabel4.setBounds(150, -10, 140, 70);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 0));
        jLabel6.setText("TENIS");
        panelsuperior.add(jLabel6);
        jLabel6.setBounds(150, 0, 120, 50);

        jLabel8.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jLabel8ComponentRemoved(evt);
            }
        });
        panelsuperior.add(jLabel8);
        jLabel8.setBounds(10, 0, 80, 60);

        getContentPane().add(panelsuperior);
        panelsuperior.setBounds(0, 0, 410, 60);

        loguear.setBackground(new java.awt.Color(188, 245, 39));
        loguear.setLayout(null);

        usuario.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        loguear.add(usuario);
        usuario.setBounds(120, 90, 140, 24);

        registrar.setBackground(new java.awt.Color(188, 245, 39));
        registrar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        registrar.setForeground(new java.awt.Color(0, 51, 51));
        registrar.setText("<html><u>registrar nuevo usuario</u></html>");
        registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrarMouseExited(evt);
            }
        });
        registrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                registrarKeyPressed(evt);
            }
        });
        registrar.setOpaque(true);
        loguear.add(registrar);
        registrar.setBounds(120, 200, 170, 16);

        textouser.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        textouser.setForeground(new java.awt.Color(0, 51, 51));
        textouser.setText("Usuario: ");
        loguear.add(textouser);
        textouser.setBounds(20, 90, 80, 20);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Contraseña: ");
        loguear.add(jLabel3);
        jLabel3.setBounds(20, 130, 90, 18);

        contraseña.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaActionPerformed(evt);
            }
        });
        loguear.add(contraseña);
        contraseña.setBounds(120, 130, 140, 24);

        mostrar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        mostrar.setText("mostrar");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        loguear.add(mostrar);
        mostrar.setBounds(280, 130, 100, 22);

        jButton1.setText("INICIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        loguear.add(jButton1);
        jButton1.setBounds(160, 170, 72, 23);

        Texto.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Texto.setText("Introduzca sus credenciales para acceder:");
        loguear.add(Texto);
        Texto.setBounds(20, 20, 300, 40);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        loguear.add(jLabel7);
        jLabel7.setBounds(280, 170, 70, 40);

        getContentPane().add(loguear);
        loguear.setBounds(0, 60, 410, 230);

        jPanel3.setBackground(new java.awt.Color(102, 153, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 290, 410, 30);

        setSize(new java.awt.Dimension(410, 315));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        login.comprobarcontraseña(mostrar, contraseña);
    }//GEN-LAST:event_mostrarActionPerformed

    private void registrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registrarKeyPressed

    }//GEN-LAST:event_registrarKeyPressed

    private void registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarMouseClicked
        CrearUsuario ventana = new CrearUsuario(usuario.getText(), contraseña.getText());
        ventana.show();
        this.dispose();
    }//GEN-LAST:event_registrarMouseClicked

    private void contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaActionPerformed

    private void jLabel1VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jLabel1VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1VetoableChange

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jLabel1.setBackground(new java.awt.Color(142, 50, 0));
        jLabel1.setForeground(Color.black);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        jLabel1.setBackground(new java.awt.Color(245,225,39));
        jLabel1.setForeground(Color.black);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrame j = this;
        login.logueo(usuario, contraseña, j);
        CambiarDatos c = new CambiarDatos(usuario.getText(), contraseña.getText());
     }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setBackground(new java.awt.Color(240, 255, 66));
        jLabel2.setForeground(Color.black);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setBackground(new java.awt.Color(245,225,39));
        jLabel2.setForeground(Color.black);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setBackground(new java.awt.Color(84, 180, 53));
        jLabel5.setForeground(Color.black);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setBackground(new java.awt.Color(245,225,39));
        jLabel5.setForeground(Color.black);
    }//GEN-LAST:event_jLabel5MouseExited


    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        JOptionPane.showMessageDialog(null, "Si quieres entrar como administrador, el usuario es: profesor y la contraseña: 123", "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabel8ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8ComponentRemoved

    private void registrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarMouseEntered
        registrar.setBackground(new java.awt.Color(245,225,39));
        registrar.setForeground(Color.black);
    }//GEN-LAST:event_registrarMouseEntered

    private void registrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarMouseExited
        registrar.setBackground(new java.awt.Color(188,245,39));
        registrar.setForeground(Color.black);
    }//GEN-LAST:event_registrarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Texto;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel loguear;
    private javax.swing.JCheckBox mostrar;
    private javax.swing.JTextField palabra;
    private javax.swing.JPanel panelsuperior;
    private javax.swing.JLabel registrar;
    private javax.swing.JLabel textouser;
    private javax.swing.JTextField userinv;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
