/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectotenis;

import proyectotenis.*;
import javax.swing.ImageIcon;

/**
 *
 * @author PC-MARTS
 */
public class juego extends javax.swing.JFrame{

    private final Methods m = new Methods();
    
    /**
     * Creates new form Execute
     */
    public juego() {
        initComponents();
        this.whoWin.setText("-");
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        piedra = new javax.swing.JButton();
        papel = new javax.swing.JButton();
        tijera = new javax.swing.JButton();
        namePlayer = new javax.swing.JLabel();
        scorePlayer = new javax.swing.JLabel();
        nameComputer = new javax.swing.JLabel();
        scoreComputer = new javax.swing.JLabel();
        whoWin = new javax.swing.JLabel();
        sacaComputer = new javax.swing.JLabel();
        sacaPlayer = new javax.swing.JLabel();
        fondoLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(943, 506));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(940, 490));
        getContentPane().setLayout(null);

        piedra.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrador\\OneDrive\\Escritorio\\Grado Superior\\2ºDAM\\Desarrollo de Interfaces\\ProyectoTenisMaven\\ProyectoTenisMaven\\proyectotenis\\src\\main\\java\\fotos\\piedra.png")); // NOI18N
        piedra.setMaximumSize(new java.awt.Dimension(64, 64));
        piedra.setMinimumSize(new java.awt.Dimension(64, 64));
        piedra.setPreferredSize(new java.awt.Dimension(64, 64));
        piedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piedraActionPerformed(evt);
            }
        });
        getContentPane().add(piedra);
        piedra.setBounds(40, 390, 64, 64);

        papel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrador\\OneDrive\\Escritorio\\Grado Superior\\2ºDAM\\Desarrollo de Interfaces\\ProyectoTenisMaven\\ProyectoTenisMaven\\proyectotenis\\src\\main\\java\\fotos\\papel.png")); // NOI18N
        papel.setMaximumSize(new java.awt.Dimension(64, 64));
        papel.setMinimumSize(new java.awt.Dimension(64, 64));
        papel.setPreferredSize(new java.awt.Dimension(64, 64));
        papel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papelActionPerformed(evt);
            }
        });
        getContentPane().add(papel);
        papel.setBounds(130, 390, 64, 64);

        tijera.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrador\\OneDrive\\Escritorio\\Grado Superior\\2ºDAM\\Desarrollo de Interfaces\\ProyectoTenisMaven\\ProyectoTenisMaven\\proyectotenis\\src\\main\\java\\fotos\\tijera.png")); // NOI18N
        tijera.setMaximumSize(new java.awt.Dimension(64, 64));
        tijera.setMinimumSize(new java.awt.Dimension(64, 64));
        tijera.setPreferredSize(new java.awt.Dimension(64, 64));
        tijera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tijeraActionPerformed(evt);
            }
        });
        getContentPane().add(tijera);
        tijera.setBounds(220, 390, 64, 64);

        namePlayer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namePlayer.setForeground(new java.awt.Color(255, 255, 255));
        namePlayer.setText("PLAYER ");
        getContentPane().add(namePlayer);
        namePlayer.setBounds(10, 80, 80, 20);

        scorePlayer.setBackground(new java.awt.Color(255, 255, 255));
        scorePlayer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        scorePlayer.setForeground(new java.awt.Color(255, 255, 255));
        scorePlayer.setText("0");
        getContentPane().add(scorePlayer);
        scorePlayer.setBounds(30, 100, 20, 30);

        nameComputer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameComputer.setForeground(new java.awt.Color(255, 255, 255));
        nameComputer.setText("COMPUTER");
        getContentPane().add(nameComputer);
        nameComputer.setBounds(830, 90, 100, 17);

        scoreComputer.setBackground(new java.awt.Color(255, 255, 255));
        scoreComputer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        scoreComputer.setForeground(new java.awt.Color(255, 255, 255));
        scoreComputer.setText("0");
        getContentPane().add(scoreComputer);
        scoreComputer.setBounds(870, 110, 20, 30);

        whoWin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        whoWin.setForeground(new java.awt.Color(255, 255, 255));
        whoWin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(whoWin);
        whoWin.setBounds(0, 30, 940, 40);
        getContentPane().add(sacaComputer);
        sacaComputer.setBounds(590, 150, 220, 150);
        getContentPane().add(sacaPlayer);
        sacaPlayer.setBounds(50, 160, 220, 150);

        fondoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrador\\OneDrive\\Escritorio\\Grado Superior\\2ºDAM\\Desarrollo de Interfaces\\ProyectoTenisMaven\\ProyectoTenisMaven\\proyectotenis\\src\\main\\java\\fotos\\fondo_1.png")); // NOI18N
        getContentPane().add(fondoLabel);
        fondoLabel.setBounds(0, 30, 930, 460);

        jPanel4.setBackground(new java.awt.Color(102, 153, 0));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 51));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jLabel3.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jLabel3VetoableChange(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel4.setText("-");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setText("❐");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(854, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 930, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void piedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piedraActionPerformed
       //TIRA MAQUINA
       int valorMaquina = m.turnoMaquina();
       //PINTO VALORES DE PLAYER
       this.sacaPlayer.setIcon(m.traductorTurnero(0));
       this.sacaPlayer.repaint();
       //PINTO VALORES DE COMPUTER
       this.sacaComputer.setIcon(m.traductorTurnero(valorMaquina));
       this.sacaComputer.repaint();
       //QUIEN GANO
       String Ganador = m.versus(0, valorMaquina);
       this.whoWin.setText(Ganador);
       m.contadorDeVictorias(Ganador);
       //CONTADOR DE PUNTOS
       this.scoreComputer.setText(Integer.toString(m.getGanaComputer()));
       this.scorePlayer.setText(Integer.toString(m.getGanaPlayer()));
    }//GEN-LAST:event_piedraActionPerformed

    private void papelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papelActionPerformed
       //TIRA MAQUINA
       int valorMaquina = m.turnoMaquina();
       //PINTO VALORES DE PLAYER
       this.sacaPlayer.setIcon(m.traductorTurnero(1));
       this.sacaPlayer.repaint();
       //PINTO VALORES DE COMPUTER
       this.sacaComputer.setIcon(m.traductorTurnero(valorMaquina));
       this.sacaComputer.repaint();
       //QUIEN GANO
       String Ganador = m.versus(1, valorMaquina);
       this.whoWin.setText(Ganador);
       m.contadorDeVictorias(Ganador);
       //CONTADOR DE PUNTOS 
       this.scoreComputer.setText(Integer.toString(m.getGanaComputer()));
       this.scorePlayer.setText(Integer.toString(m.getGanaPlayer()));
    }//GEN-LAST:event_papelActionPerformed

    private void tijeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tijeraActionPerformed
       //TIRA MAQUINA
       int valorMaquina = m.turnoMaquina();
       //PINTO VALORES DE PLAYER
       this.sacaPlayer.setIcon(m.traductorTurnero(2));
       this.sacaPlayer.repaint();
       //PINTO VALORES DE COMPUTER
       this.sacaComputer.setIcon(m.traductorTurnero(valorMaquina));
       this.sacaComputer.repaint();
       //QUIEN GANO
       String Ganador = m.versus(2, valorMaquina);
       this.whoWin.setText(Ganador);
       m.contadorDeVictorias(Ganador);
       //CONTADOR DE PUNTOS
       this.scoreComputer.setText(Integer.toString(m.getGanaComputer()));
       this.scorePlayer.setText(Integer.toString(m.getGanaPlayer()));
    }//GEN-LAST:event_tijeraActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jLabel3VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3VetoableChange

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondoLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel nameComputer;
    private javax.swing.JLabel namePlayer;
    private javax.swing.JButton papel;
    private javax.swing.JButton piedra;
    private javax.swing.JLabel sacaComputer;
    private javax.swing.JLabel sacaPlayer;
    private javax.swing.JLabel scoreComputer;
    private javax.swing.JLabel scorePlayer;
    private javax.swing.JButton tijera;
    private javax.swing.JLabel whoWin;
    // End of variables declaration//GEN-END:variables
}
